model_name: MTNet
# Device
device: "cuda" # or "cpu"

# Model hyper-parameters
n_time_slot: 4
user_embed_dim: 128
POI_embed_dim: 128
cat_embed_dim: 32
K_cluster: 60
coo_embed_dim: 32
embed_dropout: 0.4
model_dropout: 0.6
h_size: 512

# Training hyper-parameters
batch_size: 1024
accumulation_steps: 32

num_epochs: 50

lr: 0.001
lr_step_size: 6
lr_gamma: 0.9
weight_decay: 0.0001

# Experiment configuration
plot_tree: false

val_while_train: True
patience: 5
