sweep:
    lr: [0.01, 0.001, 0.0001]
    weight_decay: [0.01, 0.001, 0.0001]
    num_epochs: [150]
    transformer_dropout: [0.3, 0.4, 0.5]
    patience: [10]

naming: e{num_epochs}-p{patience}-lr{lr}-wd{weight_decay}-td{transformer_dropout}


# python ./auto_run.py inject-run --model iPCM --dataset NYC --spec ./model/iPCM/auto_run.yaml