sweep:
    time_conv_kernel_size: [1, 3, 5, 7]
    cheb_k: [2, 3, 4]
    dropout: [0.1, 0.2, 0.3, 0.4, 0.5]
    lr: [0.0001, 0.0001, 0.001]

naming: STGCN_time{time_conv_kernel_size}_cheb{cheb_k}_drop{dropout}_lr{lr}

# python ./auto_run.py inject-run --model STGCN --dataset NYC --spec ./model/STGCN/auto_run.yaml