sweep:
    learning_rate: [0.01, 0.001, 0.0001]
    hidden_size: [64, 128, 256, 512, 1024]

naming: STRNN_LR{learning_rate}_HS{hidden_size}

# python ./auto_run.py inject-run --model STRNN --dataset NYC --spec ./model/STRNN/auto_run.yaml