n_jobs: 1
device: cuda:2

enable_ssl: true  # whether enable contrastive learning
neg_weight: 1

lr: 0.001
epoch: 25

expansion: 4
mask_prop: 0.0
loss_delta: 1e-3
tfp_layer_num: 1
lstm_layer_num: 2
dropout: 0.0
head_num: 1
embed_size: 64
